feature/ auth + emails + tests
prototype2010/auction pull request #2
Opened 2020-04-06 11:46 UTC by prototype2010

2020-04-08 14:44 UTC, GerashenkoVladimir requested changes

2020-04-08 14:44 UTC, GerashenkoVladimir commented on .gitignore
>  database/*.sqlite
не на postgres делаешь?

2020-04-08 14:44 UTC, GerashenkoVladimir commented on app/Controllers/Http/AuthController.js
> +    response.status(200);
response.status(200).send({ message: 'Logged out successfully' })
можно зачейнить

2020-04-08 14:44 UTC, GerashenkoVladimir commented on app/Controllers/Http/AuthController.js
> +      user.isTokenUsed = false;
по сути после использования можно просто удалять токен

2020-04-08 14:44 UTC, GerashenkoVladimir commented on app/Controllers/Http/AuthController.js
> +    const user = await User.findBy('email', email);
можно делать findByOrFail  и отлавливать ошибки внутри еррор хендлера и там уже формировать 404
и можно будет переиспользовать это по всему коду

2020-04-08 14:44 UTC, GerashenkoVladimir commented on app/Controllers/Http/UserController.js
> +    Event.fire('user::new', user.toJSON());
было бы логично что бы создание юзера было в том же контроллере где логин и тд

2020-04-08 14:44 UTC, GerashenkoVladimir commented on app/Controllers/Http/UserController.js
> +    Event.fire('user::new', user.toJSON());
пароль в валидаторе не проверяется на повтор

2020-04-08 14:44 UTC, GerashenkoVladimir commented on app/Controllers/Http/UserController.js
> +      return response.send({
можно просто 403 Forbidden
или вообще сделать что то типа users/profile что бы не давать даже потенциальной возможности запросить чьи то данные кроме своих

2020-04-08 14:44 UTC, GerashenkoVladimir commented on start/routes.js
> +Route.post('users', 'UserController.store').validator('UserStore');
на ресурсные тоже можно вешать валидаторы 
не обязательно объявлять их отдельно

2020-04-08 14:44 UTC, GerashenkoVladimir commented on start/routes.js
> +  .only(['show', 'update'])
апдейт не валидируешь (не забудь повтор пароля)

2020-04-08 14:44 UTC, GerashenkoVladimir commented on start/routes.js
> +  Route.get('password-recovery/:token', 'AuthController.applyPasswordRecovery');
почему гет методом?

2020-04-08 14:44 UTC, GerashenkoVladimir commented on app/Controllers/Http/AuthController.js
> +  async passwordRecovery({ request, response }) {
тут у нас скорее инициируем процедуру сброса пароля

2020-04-08 14:44 UTC, GerashenkoVladimir commented on app/Controllers/Http/UserController.js
> +    authUser.email = email;
authUser.merge() мне больше нравится чем каждое поле отдельно сетить

2020-04-08 14:44 UTC, GerashenkoVladimir commented on database/migrations/1583246912383_lots_schema.js
> +    this.table('lots', (table) => {
если меняешь что то например по стилю (то что не касается функционала) отдельным комитом делай

2020-04-08 14:44 UTC, GerashenkoVladimir commented on resources/views/emails/passwordChanged.edge
> +  Password changed successfully. New password : {{ password }}
пароль категорически нельзя слать! только если ты шлеш какой то временный
но мне подход временных паролей не нравится, не секьюрно

2020-04-08 14:44 UTC, GerashenkoVladimir commented on resources/views/emails/passwordRecovery.edge
> +  to reset your password follow users/auth/lost-password/{{ passwordRecoveryToken }}
ссылка не рабочая
хоста ж нет

2020-04-08 14:44 UTC, GerashenkoVladimir commented on start/events.js
> +/* eslint-disable */
ивенты хендлеры лучше отдельно объявлять
в папке app/EventListeners например
а тут их просто конектить

2020-04-08 14:44 UTC, GerashenkoVladimir commented on start/events.js
> +const APP_EMAIL = Env.get('MAIL_USERNAME');
тут скорее какой то саппорт имейл

2020-04-08 14:44 UTC, GerashenkoVladimir commented on test/functional/auth.spec.js
> +    .loginVia(body, 'jwt')
.loginVia(body) этого достаточно

2020-04-08 14:44 UTC, GerashenkoVladimir commented on test/functional/auth.spec.js
> +  const { body } = await createUserWithParams(client);
а почему боди? там же юзер?

2020-04-08 14:44 UTC, GerashenkoVladimir commented on test/functional/auth.spec.js
> +    .loginVia({ id: notExistingUserId }, 'jwt')
вообще не имеет смысла .loginVia({ id: notExistingUserId }, 'jwt')
это апи тестов 
просто без вызова этого метода можно, будет достаточно

2020-04-08 14:44 UTC, GerashenkoVladimir commented on test/functional/auth.spec.js
> +  const { body: newTokenInfo } = await client
просто вызови сами сервисы а не дергай котроллер, оверхед в данном контексте

2020-04-08 14:44 UTC, GerashenkoVladimir commented on test/utils.js
> +  const response = await client
это серьезный оверхед при том зависим от трейта апи клиента 
если тебе надо что то такое намутить просто заимпорти сервисы

2020-04-08 14:44 UTC, GerashenkoVladimir commented on test/functional/auth.spec.js
> +  const { body } = await getUserToken(client);
ты тут путаяешь логаут с ревоук рефреш токена

2020-04-08 14:44 UTC, GerashenkoVladimir commented on test/functional/auth.spec.js
> +// / new
удалить

2020-04-08 14:44 UTC, GerashenkoVladimir commented on test/utils.js
> +  await new Promise((res) => setTimeout(res, 200));
это костыль
надо фейкать мейлер и евенты
есть механизмы в фреймворке

2020-04-08 14:44 UTC, GerashenkoVladimir commented on test/utils.js
> +  const fakeUser = await Factory.get('App/Models/User').make();
почему просто через const fakeUser = await Factory.get('App/Models/User').create(); не создать?

2020-04-08 14:44 UTC, GerashenkoVladimir commented on test/utils.js
> +  const lastEmail = await getRecentEmail();
https://www.npmjs.com/package/chai-html

2020-04-08 14:44 UTC, GerashenkoVladimir commented on test/functional/auth.spec.js
> +test('Email contains recovery code', async ({ client, assert }) => {
я обычно ивент хендлеры  тестирую отдельно от самой фичи
тут чисто проверяю что упало в список ивентов

2020-04-08 14:44 UTC, GerashenkoVladimir commented on test/functional/user.spec.js
> +  response.assertStatus(422);
респонс боди тоже проверяй
для фронта важно знать что за ошибка, да и тебе тоже

2020-05-06 07:41 UTC, prototype2010 commented on app/Controllers/Http/AuthController.js
> +    response.status(200);
+

2020-05-06 07:52 UTC, prototype2010 commented on database/migrations/1583246912383_lots_schema.js
> +    this.table('lots', (table) => {
+

2020-05-06 07:53 UTC, prototype2010 commented on resources/views/emails/passwordRecovery.edge
> +  to reset your password follow users/auth/lost-password/{{ passwordRecoveryToken }}
я же локалхост не могу написать )

2020-05-06 07:59 UTC, prototype2010 commented on app/Controllers/Http/UserController.js
> +    Event.fire('user::new', user.toJSON());
+

2020-05-07 16:22 UTC, prototype2010 commented on app/Controllers/Http/UserController.js
> +      return response.send({
+

2020-05-07 16:25 UTC, prototype2010 commented on app/Controllers/Http/UserController.js
> +    authUser.email = email;
+

2020-05-07 17:02 UTC, prototype2010 commented on app/Controllers/Http/UserController.js
> +    Event.fire('user::new', user.toJSON());
+

2020-05-07 17:04 UTC, prototype2010 commented on start/events.js
> +const APP_EMAIL = Env.get('MAIL_USERNAME');
+

2020-05-07 17:05 UTC, prototype2010 commented on start/routes.js
> +  Route.get('password-recovery/:token', 'AuthController.applyPasswordRecovery');
удобно - перешел по ссылке и попал на форму сброса пароля

2020-05-08 05:01 UTC, prototype2010 commented on app/Controllers/Http/AuthController.js
> +  async passwordRecovery({ request, response }) {
+

2020-07-08 08:00 UTC, prototype2010 commented on .gitignore
>  database/*.sqlite
+

2020-07-08 08:08 UTC, prototype2010 commented on app/Controllers/Http/AuthController.js
> +      user.isTokenUsed = false;
+

2020-07-08 08:50 UTC, prototype2010 commented on app/Controllers/Http/AuthController.js
> +    const user = await User.findBy('email', email);
+

2020-07-08 09:01 UTC, prototype2010 commented on test/utils.js
> +  await new Promise((res) => setTimeout(res, 200));
+

2020-07-08 09:01 UTC, prototype2010 commented on test/utils.js
> +  const fakeUser = await Factory.get('App/Models/User').make();
+

2020-07-08 09:09 UTC, prototype2010 commented on test/utils.js
> +  const lastEmail = await getRecentEmail();
+

2020-07-08 09:13 UTC, prototype2010 commented on test/functional/user.spec.js
> +  response.assertStatus(422);
+

2020-07-08 09:15 UTC, prototype2010 commented on test/functional/auth.spec.js
> +test('Email contains recovery code', async ({ client, assert }) => {
думаю что на будущее так и сделаю

2020-07-08 11:38 UTC, merged